name: roveassist
version: 1.0.0+1
publish_to: none
description: An application that assists all kinds of rove.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  
  
  #state management
  get: 4.3.8
  
  #local_storage
  get_storage: ^2.0.2
  
  #UI
  flutter_displaymode: ^0.3.2

  animations: ^2.0.0
  animated_text_kit: ^4.2.1
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.4.1
  
  #map
  google_maps_flutter: ^2.0.6
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.7.0
  
  #firebase
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.3
  google_sign_in: ^5.1.1
  
  #util
  introduction_screen: ^2.1.0
  fancy_bottom_navigation: ^0.3.3
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.1.0
  
  #icon
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2
  
  
  flutter: 
    sdk: flutter
  http: ^0.13.4

get_cli:
  sub_folder: false
  
  
  
  

  
  
  
  


dev_dependencies: 
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/splash_icon.png
  android: true
  ios: true
  
flutter_icons:
  image_path: "assets/images/logo/logoicon.png"
  android: true
  ios: true

flutter: 
  uses-material-design: true
  assets:
    #- .env
    - assets/images/
    - assets/images/logo/
    - assets/images/onboard_image/
    - assets/images/other_image/
    - assets/icons/
    
    # - assets/json/

